ServerEvents.recipes(event => {
    event.recipes.gtceu.large_chemical_reactor('titanaugite_titanium_impure')
        .itemInputs('2x gtceu:carbon_dust', 'gtceu:titanaugite_dust')
        .inputFluids('gtceu:chlorine 4000')
        .itemOutputs('gtceu:sial_dust')
        .outputFluids('gtceu:hot_impure_titanium_tetrachloride 3000')
        .duration(400)
        .EUt(480)

    event.recipes.gtceu.large_chemical_reactor('rutile_titanium_impure')
        .itemInputs('2x gtceu:carbon_dust', 'gtceu:rutile_dust')
        .inputFluids('gtceu:chlorine 4000')
        .outputFluids('gtceu:hot_impure_titanium_tetrachloride 3000')
        .duration(400)
        .EUt(480)

    event.recipes.gtceu.vacuum_freezer('cool_ticl4')
        .inputFluids('gtceu:hot_impure_titanium_tetrachloride 48000')
        .outputFluids('gtceu:impure_titanium_tetrachloride 48000')
        .duration(960)
        .EUt(480)

    event.recipes.gtceu.distillation_tower('distill_ticl4')
        .inputFluids('gtceu:impure_titanium_tetrachloride 48000')
        .chancedOutput('gtceu:iron_dust', 2500, 500)
        .outputFluids('gtceu:titanium_tetrachloride 16000', 'gtceu:carbon_monoxide 32000')
        .duration(960)
        .EUt(480)

    event.recipes.gtceu.electric_blast_furnace('cook_titansponge')
        .itemInputs('2x gtceu:magnesium_dust')
        .inputFluids('gtceu:titanium_tetrachloride 1000')
        .itemOutputs('kubejs:titanium_sponge')
        .blastFurnaceTemp(2141)
        .duration(800)
        .EUt(480)

    event.recipes.gtceu.macerator('macerate_titansponge')
        .itemInputs('kubejs:titanium_sponge')
        .itemOutputs( '6x gtceu:magnesium_chloride_dust', 'gtceu:titanium_dust')
        .chancedOutput('gtceu:titanium_dust', 500, 500)
        .duration(400)
        .EUt(2)
});