ServerEvents.recipes(event => {
    event.remove({id: 'gtceu:centrifuge/decomposition_centrifuging__redstone'})
    event.remove({id: 'gtceu:smelting/smelt_dust_dense_low_grade_terralite_superconductor_to_ingot'})

    event.remove({id: 'gtceu:shaped/mv_lathe'})
    event.remove({id: 'gtceu:shaped/mv_macerator'})
    event.remove({id: 'gtceu:shaped/mv_rock_crusher'})
    event.remove({id: 'gtceu:shaped/mv_block_breaker'})
    event.remove({id: 'gtceu:shaped/lv_macerator'})
    event.remove({id: 'gtceu:shaped/lv_rock_crusher'})
    event.remove({id: 'gtceu:shaped/lv_block_breaker'})
    event.remove({id: 'gtceu:shaped/lv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/mv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/hv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/ev_world_accelerator'})
    event.remove({id: 'gtceu:shaped/iv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/luv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/zpm_world_accelerator'})
    event.remove({id: 'gtceu:shaped/uv_world_accelerator'})
    
    event.remove({id: 'toms_storage:storage_terminal'})
    event.remove({id: 'toms_storage:inventory_connector'})
    event.remove({id: 'toms_storage:inventory_cable_connector'})
    event.remove({id: 'toms_storage:inventory_cable_connector_filtered'})

    event.remove({id: 'ae2:smelting/silicon_from_certus_quartz_dust'})
    event.remove({id: 'ae2:blasting/silicon_from_certus_quartz_dust'})
    event.remove({id: 'ae2:decorative/quartz_glass'})
    event.remove({id: 'ae2:decorative/quartz_vibrant_glass'})
    event.remove({id: 'ae2:network/crafting/patterns_blank'})
    event.remove({id: 'ae2:network/cables/glass_fluix'})
    event.remove({id: 'ae2:network/parts/quartz_fiber_part'})
    event.remove({id: 'ae2:misc/fluixpearl'})
    event.remove({id: 'ae2:network/blocks/energy_vibration_chamber'})
    event.remove({id: 'ae2:network/crystal_resonance_generator'})
    event.remove({id: 'ae2:network/blocks/crystal_processing_growth_accelerator'})
    event.remove({id: 'ae2:network/blocks/inscribers'})
    event.remove({id: 'ae2:network/blocks/crystal_processing_charger'})
    event.remove({id: 'ae2:network/blocks/spatial_anchor'})

    event.remove({id: 'functionalstorage:netherite_upgrade'})
    event.remove({id: 'functionalstorage:diamond_upgrade'})
    event.remove({id: 'functionalstorage:gold_upgrade'})
    event.remove({id: 'functionalstorage:copper_upgrade'})
    event.remove({id: 'functionalstorage:void_upgrade'})
    event.remove({id: 'functionalstorage:fluid_1'})
    event.remove({id: 'functionalstorage:fluid_2'})
    event.remove({id: 'functionalstorage:fluid_4'})
    event.remove({id: 'functionalstorage:linking_tool'})
    event.remove({id: 'functionalstorage:configuration_tool'})
    event.remove({id: 'functionalstorage:armory_cabinet'})
    event.remove({id: 'functionalstorage:framed_simple_compacting_drawer'})
    event.remove({id: 'functionalstorage:compacting_framed_drawer'})
    event.remove({id: 'functionalstorage:framed_storage_controller'})
    event.remove({id: 'functionalstorage:simple_compacting_drawer'})
    event.remove({id: 'functionalstorage:compacting_drawer'})
    event.remove({id: 'functionalstorage:framed_controller_extension'})
    event.remove({id: 'functionalstorage:controller_extension'})
    event.remove({id: 'functionalstorage:storage_controller'})

    event.remove({id: 'enderchests:ender_bag'})
    event.remove({id: 'enderchests:ender_pouch'})
    event.remove({id: 'endertanks:bucket'})
    event.remove({id: 'enderchests:ender_chest'})
    event.remove({id: 'endertanks:tank'})

    event.remove({id:'fluxnetworks:fluxcore'})
    event.remove({id:'fluxnetworks:fluxconfigurator'})
    event.remove({id:'fluxnetworks:fluxblock'})
    event.remove({id:'fluxnetworks:fluxcontroller'})
    event.remove({id:'fluxnetworks:basicfluxstorage'})
    event.remove({id:'fluxnetworks:herculeanfluxstorage'})
    event.remove({id:'fluxnetworks:gargantuanfluxstorage'})

    event.remove({id: 'minecraft:shears'})
    event.remove({id: 'minecraft:ender_eye'})
    event.remove({id: 'minecraft:observer'})

    event.remove({id: 'laserio:logic_chip_raw'})
    event.remove({id: 'laserio:laser_connector_advanced'})
    event.remove({id: 'laserio:card_fluid'})
    event.remove({id: 'laserio:card_item'})
    event.remove({id: 'laserio:card_redstone'})
    event.remove({id: 'laserio:card_energy'})
    event.remove({id: 'laserio:laser_wrench'})
});