ServerEvents.recipes(event => {
    event.remove({id: 'gtceu:centrifuge/decomposition_centrifuging__redstone'})
    event.remove({id: 'gtceu:smelting/smelt_dust_low_grade_terralite_superconductor_to_ingot'})
    event.remove({id: 'gtceu:alloy_smelter/alloy_smelt_low_grade_terralite_superconductor_dust_to_block'})
    event.remove({id: 'gtceu:autoclave/silicon_dioxide_to_quartzite_gem'})
    event.remove({id: 'gtceu:assembler/end_crystal'})
    event.remove({id: 'gtceu:electric_blast_furnace/titanium_from_tetrachloride'})
    event.remove({id: 'gtceu:large_chemical_reactor/titanium_tetrachloride'})
    event.remove({id: 'gtceu:chemical_reactor/titanium_tetrachloride'})
    event.remove({id: 'gtceu:coke_oven/log_to_charcoal'})
    event.remove({id: 'gtceu:arc_furnace/arc_netherite_dust'})
    event.remove({id: 'gtceu:alloy_smelter/alloy_smelt_netherite_dust_to_block'})
    event.remove({id: 'gtceu:smelting/smelt_dust_netherite_t0_ingot'})

    event.remove({id: 'gtceu:shaped/mv_lathe'})
    event.remove({id: 'gtceu:shaped/mv_macerator'})
    event.remove({id: 'gtceu:shaped/mv_rock_crusher'})
    event.remove({id: 'gtceu:shaped/mv_block_breaker'})
    event.remove({id: 'gtceu:shaped/lv_macerator'})
    event.remove({id: 'gtceu:shaped/lv_rock_crusher'})
    event.remove({id: 'gtceu:shaped/lv_block_breaker'})
    event.remove({id: 'gtceu:shaped/lv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/mv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/hv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/ev_world_accelerator'})
    event.remove({id: 'gtceu:shaped/iv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/luv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/zpm_world_accelerator'})
    event.remove({id: 'gtceu:shaped/uv_world_accelerator'})
    event.remove({id: 'gtceu:shaped/multi_furnace'})
    
    event.remove({id: 'toms_storage:storage_terminal'})
    event.remove({id: 'toms_storage:inventory_connector'})
    event.remove({id: 'toms_storage:inventory_cable_connector'})
    event.remove({id: 'toms_storage:inventory_cable_connector_filtered'})
    
    event.remove({id: 'sophisticatedbackpacks:xp_pump_upgrade'})
    event.remove({id: 'sophisticatedbackpacks:compacting_upgrade'})
    event.remove({id: 'sophisticatedbackpacks:advanced_compacting_upgrade'})
    event.remove({id: 'sophisticatedbackpacks:inception_upgrade'})
    event.remove({id: 'sophisticatedbackpacks:stack_upgrade_starter_tier'})
    event.remove({id: 'sophisticatedbackpacks:stack_upgrade_tier_1_from_starter'})
    event.remove({id: 'sophisticatedbackpacks:stack_upgrade_tier_1'})
    event.remove({id: 'sophisticatedbackpacks:stack_upgrade_tier_2'})
    event.remove({id: 'sophisticatedbackpacks:stack_upgrade_tier_3'})
    event.remove({id: 'sophisticatedbackpacks:stack_upgrade_tier_4'})
    event.remove({id: 'sophisticatedbackpacks:stack_upgrade_omega_tier'})
    event.remove({id: 'sophisticatedbackpacks:magnet_upgrade'})
    event.remove({id: 'sophisticatedbackpacks:advanced_magnet_upgrade_from_basic'})
    event.remove({id: 'sophisticatedbackpacks:advanced_magnet_upgrade'})
    event.remove({id: 'sophisticatedbackpacks:copper_backpack'})
    event.remove({id: 'sophisticatedbackpacks:iron_backpack'})
    event.remove({id: 'sophisticatedbackpacks:iron_backpack_from_copper'})
    event.remove({id: 'sophisticatedbackpacks:gold_backpack'})
    event.remove({id: 'sophisticatedbackpacks:diamond_backpack'})
    event.remove({id: 'sophisticatedbackpacks:netherite_backpack'})
    event.remove({id: 'sophisticatedbackpacks:upgrade_base'})

    event.remove({id: 'ae2:smelting/silicon_from_certus_quartz_dust'})
    event.remove({id: 'ae2:blasting/silicon_from_certus_quartz_dust'})
    event.remove({id: 'ae2:decorative/quartz_glass'})
    event.remove({id: 'ae2:decorative/quartz_vibrant_glass'})
    event.remove({id: 'ae2:network/crafting/patterns_blank'})
    event.remove({id: 'ae2:network/cables/glass_fluix'})
    event.remove({id: 'ae2:network/parts/quartz_fiber_part'})
    event.remove({id: 'ae2:misc/fluixpearl'})
    event.remove({id: 'ae2:network/blocks/energy_vibration_chamber'})
    event.remove({id: 'ae2:network/crystal_resonance_generator'})
    event.remove({id: 'ae2:network/blocks/crystal_processing_growth_accelerator'})
    event.remove({id: 'ae2:network/blocks/inscribers'})
    event.remove({id: 'ae2:network/blocks/crystal_processing_charger'})
    event.remove({id: 'ae2:network/blocks/spatial_anchor'})
    event.remove({id: 'ae2:materials/cardcapacity'})
    event.remove({id: 'ae2:materials/annihilationcore'})
    event.remove({id: 'ae2:network/blocks/storage_drive'})
    event.remove({id: 'ae2:network/parts/import_bus'})
    event.remove({id: 'ae2:network/parts/export_bus'})
    event.remove({id: 'ae2:network/blocks/interfaces_interface'})
    event.remove({id: 'ae2:network/blocks/pattern_providers_interface'})
    event.remove({id: 'ae2:network/wireless_part'})
    event.remove({id: 'ae2:network/crafting/molecular_assembler'})
    event.remove({id: 'ae2:network/blocks/cell_workbench'})
    event.remove({id: 'ae2:network/blocks/controller'})
    event.remove({id: 'ae2:network/blocks/energy_energy_acceptor'})
    event.remove({id: 'ae2:network/blocks/io_port'})
    event.remove({id: 'ae2:network/blocks/storage_chest'})
    event.remove({id: 'ae2:network/parts/tunnels_me'})
    event.remove({id: 'ae2:network/blocks/spatial_io_port'})
    event.remove({id: 'ae2:network/crafting/cpu_crafting_unit'})
    event.remove({id: 'ae2:network/cells/item_storage_components_cell_1k_part'})
    event.remove({id: 'ae2:network/cells/item_storage_components_cell_4k_part'})
    event.remove({id: 'ae2:network/cells/item_storage_components_cell_16k_part'})
    event.remove({id: 'ae2:network/cells/item_storage_components_cell_64k_part'})
    event.remove({id: 'ae2:network/cells/item_storage_components_cell_256k_part'})
    event.remove({id: 'ae2:network/blocks/io_condenser'})
    
    event.remove({id: 'expatternprovider:caner'})
    event.remove({id: 'expatternprovider:crystal_fixer'})
    event.remove({id: 'expatternprovider:ingredient_buffer'})
    event.remove({id: 'expatternprovider:tape'})
    event.remove({id: 'expatternprovider:ex_charger'})
    event.remove({id: 'expatternprovider:ex_inscriber'})
    event.remove({id: 'expatternprovider:oversize_interface'})
    event.remove({id: 'expatternprovider:wireless_tool'})

    event.remove({id: 'megacells:crafting/compression_card'})
    event.remove({id: 'megacells:crafting/decompression_module'})
    event.remove({id: 'megacells:crafting/mega_crafting_unit'})
    event.remove({id: 'megacells:cells/standard/fluid_storage_cell_64m'})
    event.remove({id: 'megacells:cells/standard/fluid_storage_cell_4m'})
    event.remove({id: 'megacells:cells/standard/fluid_storage_cell_16m'})
    event.remove({id: 'megacells:cells/standard/fluid_storage_cell_256m'})
    event.remove({id: 'megacells:cells/standard/fluid_storage_cell_1m'})
    event.remove({id: 'megacells:cells/standard/item_storage_cell_64m'})
    event.remove({id: 'megacells:cells/standard/item_storage_cell_4m'})
    event.remove({id: 'megacells:cells/standard/item_storage_cell_16m'})
    event.remove({id: 'megacells:cells/standard/item_storage_cell_256m'})
    event.remove({id: 'megacells:cells/standard/item_storage_cell_1m'})
    event.remove({id: 'megacells:cells/mega_fluid_cell_housing'})
    event.remove({id: 'megacells:cells/mega_item_cell_housing'})
    event.remove({id: 'megacells:cells/cell_component_1m'})
    event.remove({id: 'megacells:cells/cell_component_4m'})
    event.remove({id: 'megacells:cells/cell_component_16m'})
    event.remove({id: 'megacells:cells/cell_component_64m'})
    event.remove({id: 'megacells:cells/cell_component_256m'})

    event.remove({id: 'travelanchors:travel_staff'})
    event.remove({id: 'travelanchors:travel_anchor'})
    event.remove({id: 'angelring:angel_ring'})

    event.remove({id: 'functionalstorage:netherite_upgrade'})
    event.remove({id: 'functionalstorage:diamond_upgrade'})
    event.remove({id: 'functionalstorage:gold_upgrade'})
    event.remove({id: 'functionalstorage:copper_upgrade'})
    event.remove({id: 'functionalstorage:void_upgrade'})
    event.remove({id: 'functionalstorage:fluid_1'})
    event.remove({id: 'functionalstorage:fluid_2'})
    event.remove({id: 'functionalstorage:fluid_4'})
    event.remove({id: 'functionalstorage:linking_tool'})
    event.remove({id: 'functionalstorage:configuration_tool'})
    event.remove({id: 'functionalstorage:armory_cabinet'})
    event.remove({id: 'functionalstorage:framed_simple_compacting_drawer'})
    event.remove({id: 'functionalstorage:compacting_framed_drawer'})
    event.remove({id: 'functionalstorage:framed_storage_controller'})
    event.remove({id: 'functionalstorage:simple_compacting_drawer'})
    event.remove({id: 'functionalstorage:compacting_drawer'})
    event.remove({id: 'functionalstorage:framed_controller_extension'})
    event.remove({id: 'functionalstorage:controller_extension'})
    event.remove({id: 'functionalstorage:storage_controller'})

    event.remove({id: 'enderchests:ender_bag'})
    event.remove({id: 'enderchests:ender_pouch'})
    event.remove({id: 'endertanks:bucket'})
    event.remove({id: 'enderchests:ender_chest'})
    event.remove({id: 'endertanks:tank'})

    event.remove({id:'fluxnetworks:fluxcore'})
    event.remove({id:'fluxnetworks:fluxconfigurator'})
    event.remove({id:'fluxnetworks:fluxblock'})
    event.remove({id:'fluxnetworks:fluxcontroller'})
    event.remove({id:'fluxnetworks:basicfluxstorage'})
    event.remove({id:'fluxnetworks:herculeanfluxstorage'})
    event.remove({id:'fluxnetworks:gargantuanfluxstorage'})

    event.remove({id: 'minecraft:shears'})
    event.remove({id: 'minecraft:ender_eye'})
    event.remove({id: 'minecraft:observer'})
    event.remove({id: 'minecraft:end_crystal'})
    event.remove({id: 'minecraft:netherite_ingot'})
    event.remove({id: 'minecraft:netherite_scrap'})
    event.remove({id: 'minecraft:netherite_scrap_from_blasting'})

    event.remove({id: 'laserio:logic_chip_raw'})
    event.remove({id: 'laserio:laser_connector_advanced'})
    event.remove({id: 'laserio:card_fluid'})
    event.remove({id: 'laserio:card_item'})
    event.remove({id: 'laserio:card_redstone'})
    event.remove({id: 'laserio:card_energy'})
    event.remove({id: 'laserio:laser_wrench'})
});