// ServerEvents.recipes(event => {
//     event.recipes.gtceu.polarizer('polarize_certus')
//         .itemInputs('gtceu:flawless_certus_quartz_gem')
//         .itemOutputs('ae2:charged_certus_quartz_crystal')
//         .duration(150)
//         .EUt(400)
    
//     event.recipes.gtceu.alloy_smelter('quartz_glass_alloying')
//         .itemInputs('#forge:dusts/certus_quartz', '#forge:glass')
//         .itemOutputs('ae2:quartz_glass')
//         .duration(160)
//         .EUt(7)

//     event.recipes.gtceu.alloy_smelter('vib_quartz_glass_alloying')
//         .itemInputs('ae2:quartz_glass', '2x minecraft:glowstone_dust')
//         .itemOutputs('ae2:quartz_vibrant_glass')
//         .duration(160)
//         .EUt(7)
    
//     event.recipes.gtceu.large_chemical_reactor('mixing_fluix_dust_obsidian')
//         .itemInputs('16x gtceu:certus_quartz_gem', '16x gtceu:obsidian_dust', '32x minecraft:redstone')
//         .inputFluids('minecraft:water 9216')
//         .itemOutputs('64x ae2:fluix_crystal')
//         .duration(1200)
//         .EUt(1536)

//     event.recipes.gtceu.canner('pattern_canning')
//         .itemInputs('#forge:dusts/certus_quartz', '4x gtceu:fluid_cell')
//         .inputFluids('gtceu:glowstone 576')
//         .itemOutputs('4x ae2:blank_pattern')
//         .duration(20)
//         .EUt(384)

//     event.recipes.gtceu.wiremill('mill_quartz_fiber')
//         .itemInputs('ae2:quartz_glass')
//         .itemOutputs('2x ae2:quartz_fiber')
//         .duration(80)
//         .EUt(28)

//     event.recipes.gtceu.wiremill('mill_fluix')
//         .itemInputs('ae2:fluix_crystal')
//         .itemOutputs('4x ae2:fluix_glass_cable')
//         .duration(160)
//         .EUt(28)    

//     event.recipes.gtceu.mixer('fluix_pearl_dust')
//         .itemInputs('gtceu:ender_pearl_dust', '4x ae2:fluix_dust')
//         .itemOutputs('gtceu:fluix_pearl_dust')
//         .duration(160)
//         .EUt(100)

//     event.recipes.gtceu.chemical_bath('wash_cables')
//         .itemInputs('#ae2:glass_cable')
//         .inputFluids('minecraft:water 144')
//         .itemOutputs('ae2:fluix_cable')
//         .duration(40)
//         .EUt(20)

//     event.recipes.gtceu.forming_press('press_fluix_pearls')
//         .itemInputs('gtceu:fluix_pearl_dust')
//         .notConsumable('gtceu:ball_casting_mold')
//         .itemOutputs('ae2:fluix_pearl')
//         .duration(100)
//         .EUt(96)
    
//     event.recipes.gtceu.macerator('macerate_fluix')
//         .itemInputs('ae2:fluix_crystal')
//         .itemOutputs('ae2:fluix_dust')
//         .duration(200)
//         .EUt(24)

//     event.recipes.gtceu.vacuum_freezer('freeze_nitrogen')
//         .inputFluids('gtceu:nitrogen 32000')
//         .outputFluids('gtceu:liquid_nitrogen 32000')
//         .duration(640)
//         .EUt(480)

//     event.recipes.gtceu.autoclave('evil_certus')
//         .inputFluids('gtceu:liquid_nitrogen 144')
//         .itemInputs('gtceu:silicon_dioxide_dust')
//         .outputFluids('gtceu:nitrogen 144')
//         .chancedOutput('gtceu:certus_quartz_gem', 2000, 0)
//         .duration(20)
//         .EUt(480)
// });