ServerEvents.recipes(event => {
    event.recipes.gtceu.centrifuge('volcanic_ash_centri')
        .itemInputs('6x gtceu:volcanic_ash_dust')
        .itemOutputs('3x gtceu:ash_dust', "2x gtceu:obsidian_dust", "gtceu:arsenic_dust")
        .duration(40)
        .EUt(16)

    event.recipes.gtceu.electrolyzer('alumina_dust_elec')
        .itemInputs('5x gtceu:alumina_dust')
        .itemOutputs('2x gtceu:aluminium_dust')
        .outputFluids('gtceu:oxygen 3000')
        .duration(80)
        .EUt(96)

    event.recipes.gtceu.electrolyzer('dolomite_dust_elec')
        .itemInputs('11x gtceu:dolomite_dust')
        .itemOutputs('2x gtceu:carbon_dust', '2x gtceu:calcium_dust', '1x gtceu:magnesium_dust')
        .outputFluids('gtceu:oxygen 6000')
        .duration(80)
        .EUt(16)

    event.recipes.gtceu.electrolyzer('hornblende_dust_elec')
        .itemInputs('38x gtceu:hornblende_dust')
        .itemOutputs('2x gtceu:calcium_dust', '8x gtceu:sial_dust', '5x gtceu:magnesium_dust')
        .outputFluids('gtceu:oxygen 23000')
        .duration(120)
        .EUt(96)
    
    event.recipes.gtceu.centrifuge('sial_dust_elec')
        .itemInputs('2x gtceu:sial_dust')
        .itemOutputs('1x gtceu:silicon_dust', '1x gtceu:aluminium_dust')
        .duration(60)
        .EUt(64)

    event.recipes.gtceu.electromagnetic_separator('augite_blend_polar')
        .itemInputs('3x gtceu:augite_blend_dust')
        .itemOutputs('2x gtceu:augite_dust', '1x gtceu:titanaugite_dust')
        .duration(80)
        .EUt(384)

    event.recipes.gtceu.electrolyzer('augite_dust_elec')
        .itemInputs('19x gtceu:augite_dust')
        .itemOutputs('gtceu:silicon_dust', '3x gtceu:aluminium_dust', 'gtceu:magnesium_dust', '2x gtceu:calcium dust')
        .outputFluids('gtceu:oxygen 12000')
        .duration(240)
        .EUt(96)

    event.recipes.gtceu.distillery('distill_minerals')
        .inputFluids('gtceu:enriched_mineral_water 1000')
        .itemOutputs('gtceu:enriched_mineral_mixture_dust')
        .outputFluids('gtceu:distilled_water 856')
        .duration(80)
        .EUt(96)
    
    event.recipes.gtceu.centrifuge('mineral_mix_cent')
        .itemInputs('6x gtceu:enriched_mineral_mixture')
        .itemOutputs('gtceu:impure_beryllium_dust', 'gtceu:impure_pentlandite_dust', 'gtceu:impure_copper_dust', 'gtceu:impure_wulfenite_dust', 'gtceu:impure_pyrochlore_dust', 'gtceu:impure_sphalerite_dust')
        .duration(40)
        .EUt(75)
});
