ServerEvents.recipes(event => {
    event.recipes.gtceu.core_drilling('cobblestone_drilling')
        .circuit(1)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:cobblestone')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('andesite_drilling')
        .circuit(2)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:andesite')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('diorite_drilling')
        .circuit(3)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:diorite')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('schist_drilling')
        .circuit(4)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x kubejs:schist')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('deepslate_drilling')
        .circuit(5)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:deepslate')
        .duration(20)
        .EUt(16)
    
    event.recipes.gtceu.core_drilling('dripstone_drilling')
        .circuit(6)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:dripstone_block')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('granite_drilling')
        .circuit(7)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:granite')
        .duration(20)
        .EUt(16)
    
    event.recipes.gtceu.core_drilling('basalt_drilling')
        .circuit(8)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:basalt')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('tuff_drilling')
        .circuit(9)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:tuff')
        .duration(20)
        .EUt(16)
});