ServerEvents.recipes(event => {
    event.recipes.gtceu.primitive_sifter('stone_sifting_to_terralite')
        .itemInputs(Item.of('4x gtceu:stone_dust'))
        .itemOutputs('gtceu:low_grade_terralite_dust')
        .circuit(1)
        .duration(100)
        .EUt(4)

    event.recipes.gtceu.primitive_sifter('stone_sifting_to_deepslate')
        .itemInputs(Item.of('4x gtceu:stone_dust'))
        .itemOutputs(Item.of('2x gtceu:deepslate_dust'))
        .circuit(2)
        .duration(65)
        .EUt(4)

    event.recipes.gtceu.primitive_sifter('coarse_dirt_to_dirt')
        .itemInputs('minecraft:coarse_dirt')
        .itemOutputs('minecraft:dirt')
        .circuit(3)
        .duration(70)
        .EUt(4)

    event.recipes.gtceu.primitive_sifter('coarse_dirt_to_saplings1')
        .itemInputs('minecraft:coarse_dirt')
        .circuit(1)
        .chancedOutput('minecraft:oak_sapling', 2500, 0)
        .chancedOutput('minecraft:spruce_sapling', 2500, 0)
        .chancedOutput('minecraft:birch_sapling', 2500, 0)
        .chancedOutput('minecraft:jungle_sapling', 2500, 0)
        .duration(80)
        .EUt(4)

    event.recipes.gtceu.primitive_sifter('coarse_dirt_to_saplings2')
        .itemInputs('minecraft:coarse_dirt')
        .circuit(2)
        .chancedOutput('minecraft:dark_oak_sapling', 2500, 0)
        .chancedOutput('minecraft:acacia_sapling', 2500, 0)
        .chancedOutput('minecraft:cherry_sapling', 2500, 0)
        .chancedOutput('gtceu:rubber_sapling', 2500, 0)
        .duration(80)
        .EUt(4)

    event.recipes.gtceu.primitive_sifter('woodpulp_to_chad')
        .itemInputs('8x gtceu:wood_dust')
        .itemOutputs('4x gtceu:paper_dust', '2x kubejs:plant_fibers', 'gtceu:sticky_resin')
        .duration(60)
        .EUt(3)
        
    event.recipes.gtceu.sifter('plant_balls_to_fiber')
        .itemInputs('gtceu:plant_ball')
        .itemOutputs('4x kubejs:plant_fiber')
        .duration(200)
        .EUt(7)
});