ServerEvents.recipes(event => {
    event.recipes.gtceu.primitive_mixer('coarse_dirt')
        .itemInputs('minecraft:gravel', 'minecraft:dirt')
        .itemOutputs('2x minecraft:coarse_dirt')
        .duration(20)
        .EUt(2)

    event.recipes.gtceu.primitive_mixer('red_alloy_dust')
        .itemInputs('gtceu:copper_dust', '4x minecraft:redstone')
        .itemOutputs('gtceu:red_alloy_dust')
        .circuit(2)
        .duration(80)
        .EUt(4)
        
    event.recipes.gtceu.primitive_mixer('prim_mud_mix')
        .itemInputs('minecraft:dirt')
        .inputFluids('minecraft:water 250')
        .itemOutputs('minecraft:mud')
        .duration(40)
        .EUt(2)
    
    event.recipes.gtceu.primitive_mixer('prim_bronze_mix')
        .itemInputs('gtceu:tin_dust', '3x gtceu:copper_dust')
        .itemOutputs('4x gtceu:bronze_dust')
        .duration(400)
        .EUt(7)

    event.recipes.gtceu.primitive_mixer('prim_clay_mix')
        .itemInputs('gtceu:dirt_dust')
        .inputFluids('minecraft:water 250')
        .itemOutputs('minecraft:clay_ball')
        .duration(20)
        .EUt(2)

    event.recipes.gtceu.mixer('clay_mix')
        .itemInputs('gtceu:dirt_dust')
        .inputFluids('minecraft:water 144')
        .itemOutputs('minecraft:clay_ball')
        .duration(20)
        .EUt(2)
});
