ServerEvents.recipes(event => {
    event.recipes.gtceu.core_drilling('cobblestone_drilling')
        .circuit(1)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:cobblestone')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('andesite_drilling')
        .circuit(2)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:andesite')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('diorite_drilling')
        .circuit(3)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:diorite')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('schist_drilling')
        .circuit(4)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x kubejs:schist')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('deepslate_drilling')
        .circuit(5)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:deepslate')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)
    
    event.recipes.gtceu.core_drilling('dripstone_drilling')
        .circuit(6)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:dripstone_block')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('granite_drilling')
        .circuit(7)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:granite')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)
    
    event.recipes.gtceu.core_drilling('basalt_drilling')
        .circuit(8)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:basalt')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('tuff_drilling')
        .circuit(9)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:tuff')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('blackstone_drilling_nether')
        .circuit(1)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:blackstone')
        .dimension('minecraft:the_nether')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('netherrack_drilling_nether')
        .circuit(2)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:netherrack')
        .dimension('minecraft:the_nether')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('basalt_drilling_nether')
        .circuit(3)
        .inputFluids('minecraft:water 50')
        .itemOutputs('4x minecraft:basalt')
        .dimension('minecraft:the_nether')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('cobblestone_drilling_plus_fluid')
        .circuit(1)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:cobblestone')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('andesite_drilling_plus_fluid')
        .circuit(2)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:andesite')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('diorite_drilling_plus_fluid')
        .circuit(3)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:diorite')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('schist_drilling_plus_fluid')
        .circuit(4)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x kubejs:schist')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('deepslate_drilling_plus_fluid')
        .circuit(5)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:deepslate')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)
    
    event.recipes.gtceu.core_drilling('dripstone_drilling_plus_fluid')
        .circuit(6)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:dripstone_block')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('granite_drilling_plus_fluid')
        .circuit(7)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:granite')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)
    
    event.recipes.gtceu.core_drilling('basalt_drilling_plus_fluid')
        .circuit(8)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:basalt')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('tuff_drilling_plus_fluid')
        .circuit(9)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:tuff')
        .dimension('minecraft:overworld')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('blackstone_drilling_plus_fluid_nether')
        .circuit(1)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:blackstone')
        .dimension('minecraft:the_nether')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('netherrack_drilling_plus_fluid_nether')
        .circuit(2)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:netherrack')
        .dimension('minecraft:the_nether')
        .duration(20)
        .EUt(16)

    event.recipes.gtceu.core_drilling('basalt_drilling_plus_fluid_nether')
        .circuit(3)
        .inputFluids('gtceu:drilling_fluid 50')
        .itemOutputs('16x minecraft:basalt')
        .dimension('minecraft:the_nether')
        .duration(20)
        .EUt(16)
});