ServerEvents.recipes(event => {
    event.recipes.gtceu.mixer('mixer_crystal_catalyst')
        .itemInputs('gtceu:monoammonium_phosphate_dust')
        .inputFluids('gtceu:drilling_fluid 1000')
        .outputFluids('gtceu:crystalization_catalyst_solution 1000')
        .duration(32)
        .EUt(256)

    event.recipes.gtceu.chemical_reactor('cr_react_for_map_gem')
        .inputFluids('gtceu:ammonia 1000', 'gtceu:phosphoric_acid 1000')
        .itemOutputs('4x gtceu:monoammonium_phosphate_gem')
        .duration(128)
        .EUt(64)

    event.recipes.gtceu.vacuum_freezer('vacuum_freezer_endstone')
        .inputFluids('gtceu:helium 6400')
        .itemInputs('32x minecraft:cobblestone')
        .duration(320)
        .EUt(1920)
    
    // //crystalarium replication template
    // event.recipes.gtceu.crystalarium('replicate__ore')
    //     .inputFluids('gtceu:crystalization_catalyst_solution 100')
    //     .notConsumable('gtceu:raw_')
    //     .itemInputs('64x gtceu:stone_dust')
    //     .itemOutputs('64x gtceu:raw_')
    //     .duration(1200)
    //     .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_magnetite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_magnetite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_magnetite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_cassiterite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_cassiterite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_cassiterite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_chalcopyrite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_chalcopyrite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_chalcopyrite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_diamond_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_diamond')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_diamond')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_emerald_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_emerald')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_emerald')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_galena_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_galena')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_galena')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_sapphire_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_sapphire')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_sapphire')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_sphalerite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_sphalerite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_sphalerite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_stibnite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_stibnite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_stibnite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_quartzite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_quartzite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_quartzite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_cobaltite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_cobaltite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_cobaltite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_vanadium_magnetite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_vanadium_magnetite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_vanadium_magnetite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_wulfenite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_wulfenite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_wulfenite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_ruby_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_ruby')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_ruby')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_redstone_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_redstone')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_redstone')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_tantalite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_tantalite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_tantalite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_pyrolusite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_pyrolusite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_pyrolusite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_pyrochlore_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_pyrochlore')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_pyrochlore')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_apatite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_apatite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_apatite')
        .duration(1200)
        .EUt(256)

    event.recipes.gtceu.crystalarium('replicate_sheldonite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_cooperite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_cooperite')
        .duration(1200)
        .EUt(1024)
        
    event.recipes.gtceu.crystalarium('replicate_monazite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_monazite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_monazite')
        .duration(1200)
        .EUt(1024)

    event.recipes.gtceu.crystalarium('replicate_tungstate_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_tungstate')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_tungstate')
        .duration(1200)
        .EUt(1024)


    event.recipes.gtceu.crystalarium('replicate_uraninite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_uraninite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_uraninite')
        .duration(1200)
        .EUt(4096)
    

    event.recipes.gtceu.crystalarium('replicate_ilmenite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_ilmenite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_ilmenite')
        .duration(1200)
        .EUt(1024)

    event.recipes.gtceu.crystalarium('replicate_bauxite_ore')
        .inputFluids('gtceu:crystalization_catalyst_solution 100')
        .notConsumable('gtceu:raw_bauxite')
        .itemInputs('64x gtceu:stone_dust')
        .itemOutputs('64x gtceu:raw_bauxite')
        .duration(1200)
        .EUt(1024)

    // //autoclave raw ore with lava template
    // event.recipes.gtceu.autoclave('lavaclave_raw_')
    //     .inputFluids('minecraft:lava 1000')
    //     .itemInputs('4x gtceu:_dust')
    //     .chancedOutput('gtceu:raw_', 2500, 250)
    //     .duration(600)
    //     .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_ilmenite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:ilmenite_dust')
        .chancedOutput('gtceu:raw_ilmenite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_bauxite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:bauxite_dust')
        .chancedOutput('gtceu:raw_bauxite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_quartzite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:quartzite_dust')
        .chancedOutput('gtceu:raw_quartzite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_cassiterite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:tin_dust')
        .chancedOutput('gtceu:raw_cassiterite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_diamond')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:diamond_dust')
        .chancedOutput('gtceu:raw_diamond', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_chalcopyrite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('2x gtceu:copper_dust', '2x gtceu:iron_dust')
        .chancedOutput('gtceu:raw_chalcopyrite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_chalcopyrite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:chalcopyrite_dust')
        .chancedOutput('gtceu:raw_chalcopyrite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_cooperite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:cooperite_dust')
        .chancedOutput('gtceu:raw_cooperite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_cooperite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('3x gtceu:nickel_dust', 'gtceu:platinum_dust')
        .chancedOutput('gtceu:raw_sphalerite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_monazite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('3x gtceu:rare_earth_dust', 'gtceu:phosphate_dust')
        .chancedOutput('gtceu:raw_monazite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_monazite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:monazite_dust')
        .chancedOutput('gtceu:raw_monazite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_emerald')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:emerald_dust')
        .chancedOutput('gtceu:raw_emerald', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_galena')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('2x gtceu:lead_dust', '2x gtceu:sulfur_dust')
        .chancedOutput('gtceu:raw_galena', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_galena_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:galena_dust')
        .chancedOutput('gtceu:raw_galena', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_sapphire')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:sapphire_dust')
        .chancedOutput('gtceu:raw_sapphire', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_sphalerite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('2x gtceu:zinc_dust', '2x gtceu:sulfur_dust')
        .chancedOutput('gtceu:raw_sphalerite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_sphalerite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:sphalerite_dust')
        .chancedOutput('gtceu:raw_sphalerite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_stibnite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('2x gtceu:antimony_dust', '2x gtceu:sulfur_dust')
        .chancedOutput('gtceu:raw_stibnite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_stibnite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:stibnite_dust')
        .chancedOutput('gtceu:raw_stibnite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_pentlandite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:pentlandite_dust')
        .chancedOutput('gtceu:raw_pentlandite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_cobaltite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('2x gtceu:cobalt_dust', '2x gtceu:arsenic_dust')
        .chancedOutput('gtceu:raw_cobaltite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_cobaltite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:cobaltite_dust')
        .chancedOutput('gtceu:raw_cobaltite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_vanadium_magnetite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:vanadium_magnetite_dust')
        .chancedOutput('gtceu:raw_vanadium_magnetite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_wulfenite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:wulfenite_dust')
        .chancedOutput('gtceu:raw_wulfenite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_tungstate')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:tungstate_dust')
        .chancedOutput('gtceu:raw_tungstate', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_bauxite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:aluminium_dust')
        .chancedOutput('gtceu:raw_bauxite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_ilmenite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('2x gtceu:titanium_dust', '2x gtceu:iron_dust')
        .chancedOutput('gtceu:raw_ilmenite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_ruby')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:ruby_dust')
        .chancedOutput('gtceu:raw_ruby', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_redstone')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:redstone_dust')
        .chancedOutput('gtceu:raw_redstone', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_tantalite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:tantalite_dust')
        .chancedOutput('gtceu:raw_tantalite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_pyrolusite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:manganese_dust')
        .chancedOutput('gtceu:raw_pyrolusite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_pyrolusite_2')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:pyrolusite_dust')
        .chancedOutput('gtceu:raw_pyrolusite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_uraninite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:uraninite_dust')
        .chancedOutput('gtceu:raw_uraninite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_pyrochlore')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:pyrochlore_dust')
        .chancedOutput('gtceu:raw_pyrochlore', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_apatite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:apatite_dust')
        .chancedOutput('gtceu:raw_apatite', 2500, 250)
        .duration(600)
        .EUt(1536)

    event.recipes.gtceu.autoclave('lavaclave_raw_magnetite')
        .inputFluids('minecraft:lava 1000')
        .itemInputs('4x gtceu:magnetite_dust')
        .chancedOutput('gtceu:raw_magnetite', 2500, 250)
        .duration(600)
        .EUt(1536)
});